- app: metrics-server
  env: sandbox
  namespace: observability
  chart:
    version: 5.11.7
    name: metrics-server
- app: metrics-server
  env: dev
  namespace: observability
  chart:
    version: 5.11.7
    name: metrics-server
- app: metrics-server
  env: staging
  namespace: observability
  chart:
    version: 5.11.7
    name: metrics-server
- app: metrics-server
  env: prod
  namespace: observability
  chart:
    version: 5.11.7
    name: metrics-server