app: metrics-server
namespace: observability
overrides:
- env: sandbox
  name: minikube-sandbox
  version: 6.2.1
- env: dev
  name: minikube-dev
  version: 6.2.1
# - app: metrics-server
#   name: minikube-sandbox
#   env: sandbox
#   namespace: observability
#   chart: 
#     version: 6.2.1
#     name: metrics-server
# - app: metrics-server
#   name: minikube-dev
#   env: dev
#   namespace: observability
#   chart: 
#     version: 6.2.1
#     name: metrics-server
