# This applicationset will create an application for every chart in charts/* with values in values/*
# Each chart can set defaults to apply to all env clusters
# Each chart can set overrides to apply to specific env clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .. # Ensures charts path and values path is available for templating
spec:
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - env
                - chart.name
                - chart.version
                - cluster
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/defaults.yaml
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/overrides.yaml 
          - list:
              elements:
              - chart.name: '{{ chart.name }}'
  template:
    metadata:
      name: '{{ app }}-{{ env }}-{{ chart.version }}'
      labels:
        app: "{{ app }}"
        env: "{{ env }}"
    spec:
      project: default
      destination:
        server: '{{ values.cluster }}'
        namespace: '{{ namespace }}'
      source:
        helm:
          releaseName: '{{ chart }}'
          valueFiles: # Optional cluster values file and env values file
            - '/{{ path[0] }}/values/{{ app }}/cluster/values-{{ name }}.yaml'
            - '/{{ path[0] }}/values/{{ app }}/env/values-{{ env }}.yaml'
          ignoreMissingValueFiles: true
        path: '{{ path }}/version-{{ chart.version }}'
        repoURL: https://github.com/vette1861/helm-appsets.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
