# This applicationset will create an application for every chart in charts/* with values in values/*
# Each chart can set defaults to apply to all env clusters
# Each chart can set overrides to apply to specific env clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .. # Ensures charts path and values path is available for templating
spec:
  generators:
    - merge:
        mergeKeys:
          - name
          - chart.name
          - env
        generators:
          - merge:
              mergeKeys:
                - chart.name
                - chart.version
                - chart.env
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/defaults.yaml 
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/overrides.yaml 
          - clusters:
              selector:
                matchLabels:
                  env: '{{ env }}'
              values:
                chart.name: '{{ chart.name }}'
                chart.version: '{{ chart.version }}'
                env: '{{ metadata.labels.env }}'
                namespace: '{{ namespace }}'
              # selector:
              #   matchLabels:
              #     env: '{{ env }}'
  template:
    metadata:
      name: "{{ app }}-{{ name }}-{{ values.env }}-{{ values.chart.version }}"
    spec:
      project: default
      destination:
        server: '{{ name }}'
        namespace: '{{ values.namespace }}'
      source:
        helm:
          releaseName: '{{ values.chart.name }}'
          valueFiles: # Optional cluster values file and env values file
            - '/{{ path[0] }}/values/{{ app }}/cluster/values-{{ name }}.yaml'
            - '/{{ path[0] }}/values/{{ app }}/env/values-{{ values.env }}.yaml'
          ignoreMissingValueFiles: true
        path: '{{ path }}/version-{{ values.chart.version }}'
        repoURL: https://github.com/vette1861/helm-appsets.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
