# This applicationset will create an application for every chart in charts/* with values in values/*
# Each chart can set defaults to apply to all env clusters
# Each chart can set overrides to apply to specific env clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .. # Ensures charts path and values path is available for templating
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - env
          - name
          - chartName
          - app
        generators:
          # Gets each chart in charts/ and matches service defaults to cluster
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: "charts/**/defaults.yaml"
                - clusters:
                    selector:
                      # matchLabels:
                      matchExpressions:
                      - key: env
                        operator: In
                        values: ['{{ .envList}}']
                        # env: '{{.env}}'
                    values:
                      app: '{{ .app }}'
                      basename: '{{ .path.basename }}'
                      # env: '{{ .metadata.labels.env }}'
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: "charts/**/overrides.yaml"
                - clusters:
                    selector:
                      matchExpressions:
                      - key: env
                        operator: In
                        values: ['{{ .envList}}']
                    values:
                      app: '{{ .app }}'
                      basename: '{{ .path.basename }}'
                      # env: '{{ .metadata.labels.env }}'
      selector:
        matchLabels:
          serviceType: autoDeployCoreService
  template:
    metadata:
      name: '{{ .app }}-{{ metadata.labels.env }}-{{ .name }}'
      labels:
        app: '{{ .app }}'
        env: '{{ metadata.labels.env }}'
        version: '{{ .chartVersion }}'
        path: '{{ .path.basename }}'
        serviceType: '{{ .serviceType }}'
    spec:
      project: default
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'
      source:
        helm:
          releaseName: '{{ .app }}'
          valueFiles: # Optional cluster values file and env values file
            - '/values/{{ .app }}/cluster/values-{{ .name }}.yaml'
            - '/values/{{ .app }}/env/values-{{ metadata.labels.env }}.yaml'
          ignoreMissingValueFiles: true
        path: '/{{ .path.path }}/version-{{ .chartVersion }}'
        repoURL: https://github.com/vette1861/helm-appsets.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true