# This applicationset will create an application for every chart in charts/* with values in values/*
# Each chart can set defaults to apply to all env clusters
# Each chart can set overrides to apply to specific env clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .. # Ensures charts path and values path is available for templating
spec:
  generators:
    - merge:
        mergeKeys:
          - name
          - server
          - env
          - path.basename
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/defaults.yaml 
                - clusters:
                    selector:
                      matchLabels:
                        env: '{{ env }}'
                    values:
                      chart: '{{ path.basename }}-{{ chart.version }}'
                      path: '{{ path }}'
                      env: '{{ env }}'
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/vette1861/helm-appsets.git
                    revision: HEAD
                    files:
                    - path: charts/**/overrides.yaml 
                - clusters:
                    selector:
                      matchLabels:
                        env: '{{ env }}'
                    values:
                      chart: '{{ path.basename }}-{{ chart.version }}'
                      path: '{{ path }}'
                      env: '{{ env }}'
  template:
    metadata:
      name: '{{ app }}-{{ name }}'
      labels:
        app: '{{ app }}'
        env: '{{ env }}'
        deployed: '{{ automate }}'
        version: '{{ chart.version }}'
    spec:
      project: default
      destination:
        server: '{{ server }}'
        namespace: '{{ namespace }}'
      source:
        helm:
          releaseName: '{{ app }}'
          valueFiles: # Optional cluster values file and env values file
            - '/values/{{ app }}/cluster/values-{{ name }}.yaml'
            - '/values/{{ app }}/env/values-{{ env }}.yaml'
          ignoreMissingValueFiles: true
        path: '{{ path }}/version-{{ chart.version }}'
        repoURL: https://github.com/vette1861/helm-appsets.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true