# This applicationset will create an application for every chart in charts/* with values in values/*
# Each chart can set defaults to apply to all env clusters
# Each chart can set overrides to apply to specific env clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-poc-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .. # Ensures charts path and values path is available for templating
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/vette1861/helm-appsets.git
              revision: HEAD
              files:
              - path: charts/**/overrides.yaml 
          - clusters:
              selector:
                matchLabels:
                  env: '{{ overrides.env }}'
              values:
                env: '{{ overrides.env }}'
                version: '{{ overrides.version }} '
  template:
    metadata:
      name: '{{ app }}-{{ values.env }}-{{ name }}-aa'
    spec:
      project: default
      destination:
        server: '{{ cluster }}'
        namespace: '{{ namespace }}'
      source:
        helm:
          releaseName: '{{ app }}'
          valueFiles: # Optional cluster values file and env values file
            - '/{{ path[0] }}/values/{{ app }}/cluster/values-{{ name }}.yaml'
            - '/{{ path[0] }}/values/{{ app }}/env/values-{{ values.env }}.yaml'
          ignoreMissingValueFiles: true
        path: '{{ path }}/version-{{ values.version }}'
        repoURL: https://github.com/vette1861/helm-appsets.git
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
